project:
  type: book
  output-dir: ../_site/en

lang: en

version: 1.1

book:
  title: "Guideline for Magnetic Measurement Scales for Position and Angle Measurement"
  subtitle: "Terminology, Technical Representation, Classification, Measurement Setup, Measurement, and Evaluation"

  sidebar:
    title: "INNOMAG Guideline"
    search: true
    tools:
      - icon: translate
        text: Deutsch
        href: ../de/index.html

  output-file: "Innomag-Guideline-en"

  downloads:
    - pdf

  chapters:
    - href: index.qmd
      text: "About this Document"
    - sec01-Introduction.qmd
    - sec02-Examples.qmd
    - sec03-Fundamentals.qmd
    - sec04-Structure.qmd
    - sec05-Strayfield.qmd
    - sec06-CharacterizationFundamentals.qmd
    - sec07-Classification.qmd
    - sec08-Sensors.qmd
    - literature.qmd

bibliography: ../bibliography.bib

format:
  html:
    toc: true
    number-sections: true
    theme: cosmo
    css: styles.css

  pdf:
    documentclass: scrbook
    papersize: a4
    toc: true
    toc-depth: 2
    lof: true
    lot: true
    keep-tex: false
    number-sections: true
    include-before-body: impressum.tex
    include-in-header:
      text: |
        \usepackage{tabularx}
        \usepackage{array}
