project:
  type: book
  output-dir: ../_site/de

lang: de

version: 1.1
date: 2026-10-01
doi: 10.5281/zenodo.XXXXXXX

book:
  title: "Magnetischen Maßverkörperungen für Weg- und Winkelmesssysteme"
  subtitle: "Terminologie, technische Darstellung, Einteilung, Messaufbau, Vermessung und Bewertung"

  sidebar:
    title: "INNOMAG Guideline"
    search: true
    tools:
      - icon: translate
        text: English
        href: ../en/index.html

  output-file: "Innomag-Guideline-de"

  downloads:
    - pdf

  chapters:
    - href: index.qmd
      text: "Über das Dokument"
    - sec01-Einleitung.qmd
    - sec02-Beispiele.qmd
    - sec03-Grundlagen.qmd
    - sec04-Struktur.qmd
    - sec05-Streufeld.qmd
    - sec06-Vermessungsgrundlagen.qmd
    - sec07-Einteilung.qmd
    - sec08-Sensorik.qmd
    - literatur.qmd

bibliography: ../bibliography.bib

filters:
  - at: post-quarto
    path: table-styles.lua

format:
  html:
    toc: true
    number-sections: true
    theme: cosmo
    css: styles.css

  pdf:
    documentclass: scrbook
    papersize: a4
    toc: true
    toc-depth: 2
    lof: true
    lot: true
    keep-tex: false
    number-sections: true

    include-before-body:
      - latex_impressum.tex

    include-in-header:
      - latex_preamble.tex

    template-partials:
      - before-body.tex