project:
  type: book
  output-dir: _book

lang: de

version: 1.1

book:
  title: "Richtlinie zu Magnetischen Maßverkörperungen für Weg- und Winkelmesssysteme"
  subtitle: "Terminologie, technische Darstellung, Einteilung, Messaufbau, Vermessung und Bewertung"

  sidebar:
    title: "INNOMAG Guideline"
    search: true

  output-file: "Innomag-Guideline-de"

  downloads:
    - pdf

  chapters:
    - href: index.qmd
      text: "Über das Dokument"
    - kapitel01-einleitung.qmd
    - kapitel02-beispiele.qmd
    - kapitel03-grundlagen.qmd
    - kapitel04-struktur.qmd
    - kapitel05-streufeld.qmd
    - literatur.qmd

bibliography: ../bibliography.bib

format:
  html:
    toc: true
    number-sections: true
    theme: cosmo
    css: styles.css

  pdf:
    documentclass: scrbook
    papersize: a4
    toc: true
    toc-depth: 2
    lof: true
    lot: true
    keep-tex: false
    number-sections: true
    include-before-body: impressum.tex
    include-in-header:
      text: |
        \usepackage{tabularx}
        \usepackage{array}
